import { mkdir, writeFile, copyFile, access } from "node:fs/promises";
import path from "node:path";
import { createStableId } from "@ai2live/domain";

/**
 * AutoLive2d downstream adapter (M0).
 * Writes an import package under builds/autolive2d/ — does not ship AutoLive2d itself.
 * Consumer can open the PSD + attachments-style manifest in AutoLive2d.
 */
export interface AutoLive2dBuildOptions {
  projectRoot: string;
  psdPath?: string;
  importManifestPath?: string;
  buildId?: string;
}

export interface AutoLive2dBuildResult {
  backend: "autolive2d";
  build_id: string;
  out_dir: string;
  files: string[];
  warnings: string[];
  unknown_layers: string[];
}

async function exists(p: string) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

export async function buildAutoLive2dPackage(
  opts: AutoLive2dBuildOptions
): Promise<AutoLive2dBuildResult> {
  const projectRoot = path.resolve(opts.projectRoot);
  const buildId = opts.buildId ?? createStableId("build", `al2d-${Date.now()}`);
  const outDir = path.join(projectRoot, "builds", "autolive2d", buildId);
  await mkdir(outDir, { recursive: true });

  const psdPath = opts.psdPath ?? path.join(projectRoot, "psd", "character.psd");
  const importManifestPath =
    opts.importManifestPath ?? path.join(projectRoot, "psd", "import_manifest.json");

  const warnings: string[] = [];
  const files: string[] = [];

  if (!(await exists(psdPath))) {
    throw new Error(`PSD not found: ${psdPath}. Run compile first.`);
  }
  const destPsd = path.join(outDir, "character.psd");
  await copyFile(psdPath, destPsd);
  files.push("character.psd");

  let layers: unknown[] = [];
  if (await exists(importManifestPath)) {
    const importMan = JSON.parse(await (await import("node:fs/promises")).readFile(importManifestPath, "utf8"));
    layers = importMan.layers ?? [];
    await writeFile(path.join(outDir, "import_manifest.json"), JSON.stringify(importMan, null, 2));
    files.push("import_manifest.json");
  } else {
    warnings.push("import_manifest.json missing");
  }

  // attachments.json — AutoLive2d-compatible companion metadata
  const attachments = {
    version: 1,
    source: "ai2live",
    build_id: buildId,
    note: "LEFT/RIGHT are character-own sides",
    layers: (layers as { uuid: string; psd_name: string; semantic: string; side: string; z_index: number }[]).map(
      (l) => ({
        id: l.uuid,
        name: l.psd_name,
        kind: l.semantic.toLowerCase(),
        side: l.side,
        z: l.z_index,
      })
    ),
  };
  await writeFile(path.join(outDir, "attachments.json"), JSON.stringify(attachments, null, 2));
  files.push("attachments.json");

  const readme = `# AutoLive2d import package

build_id: ${buildId}

1. Open AutoLive2d
2. Import character.psd
3. Optionally load attachments.json for semantic hints

Generated by @ai2live/autolive2d-adapter (M0).
`;
  await writeFile(path.join(outDir, "README.md"), readme);
  files.push("README.md");

  const meta = {
    backend: "autolive2d" as const,
    build_id: buildId,
    screenshots: [] as string[],
    warnings,
    unknown_layers: [] as string[],
  };
  await writeFile(path.join(outDir, "build_result.json"), JSON.stringify(meta, null, 2));
  files.push("build_result.json");

  return {
    backend: "autolive2d",
    build_id: buildId,
    out_dir: outDir,
    files,
    warnings,
    unknown_layers: [],
  };
}
